### ISSUE TITLE
Convert mongo standalone to replica set in debian

### ISSUE THREAD

**Issue by cjmling** [cjmling/findings#199]
From mongodb doc https://docs.mongodb.com/manual/tutorial/convert-standalone-to-replica-set/#procedure

but we won't actually do their way.  We will 

1.  Shut down the mongod instance by running service mongod stop 
2. Update `/etc/mongod.conf` to include replication configuration so it becomes. Basically in my case i just had to set the Replication part, didn't change other parts.
```
net:
  port: 27017
  bindIp: 127.0.0.1
systemLog:
  destination: file
  logAppend: true
  path: "/var/log/mongodb/mongod.log"
processManagement:
  fork: true
  pidFilePath: "/var/run/mongodb/mongod.pid"
storage:
  journal:
    enabled: true
  dbPath: "/mnt/data/mongodb"
  engine: wiredTiger
replication:
  replSetName: rs0
```

3. Start the mongod service again `service mongod start`
4. Get into mongo shell by running `mongo`
5. Run `rs.initiate()`

The replica set is now operational. To view the replica set configuration, use rs.conf(). To check the status of the replica set, use rs.status().
